version: "2"

services:
  db:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb:/var/lib/mysql
  #    - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here
  #  ports:
  #    - "3306:3306"

  app:
    image: wodby/drupal-php:7.0 # Allowed: 7.0, 5.6
    environment:
      DRUPAL_VERSION: 8 # Allowed: 7, 8
  #    XDEBUG_CONFIG: xdebug.remote_autostart=1
    links:
      - db
      - cache
    volumes:
      - ./docroot:/var/www/html

  web:
    image: wodby/drupal-nginx
    links:
      - app
    volumes_from:
      - app
    ports:
      - "8000:80"

  cache:
    image: redis:3.2-alpine
  #  image: memcached:1.4-alpine
  #  ports:
  #    - "6379:6379" # For redis
  ##    - "11211:11211" # For memcached
