db:
  image: wodby/drupal-mariadb
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
  volumes:
    - ./mariadb:/var/lib/mysql
#    - ./mariadb-init:/docker-entrypoint-initdb.d
app:
  image: wodby/drupal-php
  environment:
    DRUPAL_VERSION: 8 # Allowed 7, 8
  links:
    - db
  volumes:
    - ./docroot:/var/www/html
web:
  image: wodby/drupal-nginx
  links:
    - app
  volumes_from:
    - app
  ports:
        - "8000:80"
